# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: microcrud.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'microcrud.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmicrocrud.proto\x12\tmicrocrud\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bgoogle/protobuf/empty.proto\"7\n\x0e\x45ntityProtocol\x12%\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\"\x1c\n\x0e\x44\x65leteProtocol\x12\n\n\x02id\x18\x01 \x01(\t\"\x19\n\x0bGetProtocol\x12\n\n\x02id\x18\x01 \x01(\t\"G\n\rResultService\x12\x0f\n\x07message\x18\x01 \x01(\t\x12%\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct2\xcd\x02\n\nCrudEntity\x12?\n\x06\x43reate\x12\x19.microcrud.EntityProtocol\x1a\x18.microcrud.ResultService\"\x00\x12?\n\x06Update\x12\x19.microcrud.EntityProtocol\x1a\x18.microcrud.ResultService\"\x00\x12?\n\x06\x44\x65lete\x12\x19.microcrud.DeleteProtocol\x1a\x18.microcrud.ResultService\"\x00\x12=\n\x07GetById\x12\x16.microcrud.GetProtocol\x1a\x18.microcrud.ResultService\"\x00\x12=\n\x07GetData\x12\x16.google.protobuf.Empty\x1a\x18.microcrud.ResultService\"\x00\x42\x14Z\x12microcud.contractsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'microcrud_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022microcud.contracts'
  _globals['_ENTITYPROTOCOL']._serialized_start=89
  _globals['_ENTITYPROTOCOL']._serialized_end=144
  _globals['_DELETEPROTOCOL']._serialized_start=146
  _globals['_DELETEPROTOCOL']._serialized_end=174
  _globals['_GETPROTOCOL']._serialized_start=176
  _globals['_GETPROTOCOL']._serialized_end=201
  _globals['_RESULTSERVICE']._serialized_start=203
  _globals['_RESULTSERVICE']._serialized_end=274
  _globals['_CRUDENTITY']._serialized_start=277
  _globals['_CRUDENTITY']._serialized_end=610
# @@protoc_insertion_point(module_scope)
