# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import microcrud_pb2 as microcrud__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in microcrud_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CrudEntityStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/microcrud.CrudEntity/Create',
                request_serializer=microcrud__pb2.EntityProtocol.SerializeToString,
                response_deserializer=microcrud__pb2.ResultService.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/microcrud.CrudEntity/Update',
                request_serializer=microcrud__pb2.EntityProtocol.SerializeToString,
                response_deserializer=microcrud__pb2.ResultService.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/microcrud.CrudEntity/Delete',
                request_serializer=microcrud__pb2.DeleteProtocol.SerializeToString,
                response_deserializer=microcrud__pb2.ResultService.FromString,
                _registered_method=True)
        self.GetById = channel.unary_unary(
                '/microcrud.CrudEntity/GetById',
                request_serializer=microcrud__pb2.GetProtocol.SerializeToString,
                response_deserializer=microcrud__pb2.ResultService.FromString,
                _registered_method=True)
        self.GetData = channel.unary_unary(
                '/microcrud.CrudEntity/GetData',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=microcrud__pb2.ResultService.FromString,
                _registered_method=True)


class CrudEntityServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CrudEntityServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=microcrud__pb2.EntityProtocol.FromString,
                    response_serializer=microcrud__pb2.ResultService.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=microcrud__pb2.EntityProtocol.FromString,
                    response_serializer=microcrud__pb2.ResultService.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=microcrud__pb2.DeleteProtocol.FromString,
                    response_serializer=microcrud__pb2.ResultService.SerializeToString,
            ),
            'GetById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetById,
                    request_deserializer=microcrud__pb2.GetProtocol.FromString,
                    response_serializer=microcrud__pb2.ResultService.SerializeToString,
            ),
            'GetData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetData,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=microcrud__pb2.ResultService.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'microcrud.CrudEntity', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('microcrud.CrudEntity', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CrudEntity(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/microcrud.CrudEntity/Create',
            microcrud__pb2.EntityProtocol.SerializeToString,
            microcrud__pb2.ResultService.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/microcrud.CrudEntity/Update',
            microcrud__pb2.EntityProtocol.SerializeToString,
            microcrud__pb2.ResultService.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/microcrud.CrudEntity/Delete',
            microcrud__pb2.DeleteProtocol.SerializeToString,
            microcrud__pb2.ResultService.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/microcrud.CrudEntity/GetById',
            microcrud__pb2.GetProtocol.SerializeToString,
            microcrud__pb2.ResultService.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/microcrud.CrudEntity/GetData',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            microcrud__pb2.ResultService.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
